### ISSUE TITLE
v6.1.8

### ISSUE THREAD

**Issue by JayManCanada6014** [chuot/rdio-scanner#120]
Brand no 6.1.8, no importing of any old settings. The overall system auto-populate seems to be on by default. I turned it off and deleted the two systems it made and Rdio-Scanner crashed.

Jan 31 19:42:47 vmi767181 rdio-scanner[2440653]: 2022/01/31 19:42:47 newcall: system=201 talkgroup=2039 file=2039-1643676158_867637500-call_2689.wav no matching system/talkgroup
Jan 31 19:42:48 vmi767181 rdio-scanner[2440653]: 2022/01/31 19:42:48 newcall: system=201 talkgroup=1506 file=1506-1643676142_867537500-call_2686.m4a success
Jan 31 19:42:52 vmi767181 rdio-scanner[2440653]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 31 19:42:52 vmi767181 rdio-scanner[2440653]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x975b54]
Jan 31 19:42:52 vmi767181 rdio-scanner[2440653]: goroutine 31 [running]:
Jan 31 19:42:52 vmi767181 rdio-scanner[2440653]: main.(*Controller).IngestCall(0xc0000b6f00, 0xc0003b8fc0)
Jan 31 19:42:52 vmi767181 rdio-scanner[2440653]: #011/home/chuot/Dev/rdio-scanner/server/controller.go:214 +0x394
Jan 31 19:42:52 vmi767181 rdio-scanner[2440653]: main.(*Controller).Start.func2()
Jan 31 19:42:52 vmi767181 rdio-scanner[2440653]: #011/home/chuot/Dev/rdio-scanner/server/controller.go:641 +0x105
Jan 31 19:42:52 vmi767181 rdio-scanner[2440653]: created by main.(*Controller).Start
Jan 31 19:42:52 vmi767181 rdio-scanner[2440653]: #011/home/chuot/Dev/rdio-scanner/server/controller.go:637 +0x2d1
Jan 31 19:42:52 vmi767181 systemd[1]: rdio-scanner.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 31 19:42:52 vmi767181 systemd[1]: rdio-scanner.service: Failed with result 'exit-code'.

**Comment by JayManCanada6014** [comment]
And then it restarted itself as the service should and it crashed again after a bit.



Jan 31 19:42:52 vmi767181 systemd[1]: rdio-scanner.service: Failed with result 'exit-code'.
Jan 31 19:44:52 vmi767181 systemd[1]: rdio-scanner.service: Scheduled restart job, restart counter is at 2.
Jan 31 19:44:52 vmi767181 rdio-scanner[2440993]: Rdio Scanner v6.1.8
Jan 31 19:44:52 vmi767181 rdio-scanner[2440993]: ----------------------------------
Jan 31 19:44:52 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:44:52 server started
Jan 31 19:44:52 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:44:52 base folder is /opt/rdio-scanner
Jan 31 19:44:52 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:44:52 main interface at http://vmi767181:3000
Jan 31 19:44:52 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:44:52 admin interface at http://vmi767181:3000/admin
Jan 31 19:44:53 vmi767181 tailscaled[1421791]: control: HostInfo: {"IPNVersion":"1.20.2-t312750ddd-g2c164d9c7","BackendLogID":"5190f40c7c1f4cc5a1b14ca5569df2a6280bf22e9b76d1503d7c809fde47831a","OS":"linux","OSVersion":"Ubuntu 20.04.3 LTS (Focal Fossa); kernel=5.4.0-92-generic","Hostname":"vmi767181","GoArch":"amd64","Services":[{"Proto":"tcp","Port":22,"Description":"sshd -D [listener] 0 of 10-100 startups"},{"Proto":"tcp","Port":53,"Description":"systemd-resolved"},{"Proto":"tcp","Port":3000,"Description":"rdio-scanner"},{"Proto":"tcp","Port":46297,"Description":"tailscaled"},{"Proto":"peerapi4","Port":46297},{"Proto":"peerapi6","Port":46297},{"Proto":"peerapi-dns-proxy","Port":1}],"NetInfo":{"MappingVariesByDestIP":false,"HairPinning":false,"WorkingIPv6":true,"WorkingUDP":true,"UPnP":false,"PMP":false,"PCP":false,"PreferredDERP":1,"DERPLatency":{"1-v4":0.003890308,"1-v6":0.003354163,"10-v4":0.067275088,"10-v6":0.067222589,"11-v4":0.114438954,"11-v6":0.11694863,"12-v4":0.020782125,"12-v6":0.020237055,"2-v4":0.071037678,"2-v6":0.072289,"4-v4":0.097256048,"4-v6":0.08711756,"8-v4":0.07311935,"9-v4":0.040946264,"9-v6":0.041250369}}}
Jan 31 19:44:53 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:44:53 newcall: system=100 talkgroup=8224 file=8224-1643676282_142125000-call_295.m4a success
Jan 31 19:44:54 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:44:54 listeners count is 1
Jan 31 19:44:57 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:44:57 listeners count is 2
Jan 31 19:44:59 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:44:59 newcall: system=201 talkgroup=1506 file=1506-1643676282_867537500-call_2709.m4a success
Jan 31 19:45:12 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:12 newcall: system=102 talkgroup=35472 file=35472-1643676304_141525000-call_1825.wav no matching system/talkgroup
Jan 31 19:45:12 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:12 newcall: system=102 talkgroup=35440 file=35440-1643676304_141375000-call_1826.wav no matching system/talkgroup
Jan 31 19:45:15 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:15 newcall: system=102 talkgroup=35440 file=35440-1643676307_142425000-call_1827.wav no matching system/talkgroup
Jan 31 19:45:17 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:17 newcall: system=201 talkgroup=1506 file=1506-1643676298_867637500-call_2714.m4a success
Jan 31 19:45:18 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:18 newcall: system=102 talkgroup=35440 file=35440-1643676310_142005000-call_1828.wav no matching system/talkgroup
Jan 31 19:45:19 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:19 newcall: system=102 talkgroup=35456 file=35456-1643676313_141735000-call_1829.wav no matching system/talkgroup
Jan 31 19:45:20 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:20 newcall: system=102 talkgroup=35440 file=35440-1643676313_142995000-call_1830.wav no matching system/talkgroup
Jan 31 19:45:27 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:27 newcall: system=102 talkgroup=35456 file=35456-1643676318_141375000-call_1831.wav no matching system/talkgroup
Jan 31 19:45:28 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:28 newcall: system=201 talkgroup=1506 file=1506-1643676314_867537500-call_2715.m4a success
Jan 31 19:45:30 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:30 newcall: system=102 talkgroup=35440 file=35440-1643676321_141525000-call_1832.wav no matching system/talkgroup
Jan 31 19:45:33 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:33 newcall: system=102 talkgroup=35440 file=35440-1643676325_141735000-call_1835.wav no matching system/talkgroup
Jan 31 19:45:34 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:34 newcall: system=100 talkgroup=8896 file=8896-1643676325_142425000-call_1833.m4a success
Jan 31 19:45:35 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:35 newcall: system=100 talkgroup=8896 file=8896-1643676325_141435000-call_296.wav duplicate call rejected
Jan 31 19:45:36 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:36 newcall: system=102 talkgroup=35680 file=35680-1643676325_142950000-call_297.wav no matching system/talkgroup
Jan 31 19:45:38 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:38 newcall: system=201 talkgroup=1502 file=1502-1643676324_867387500-call_2718.wav no matching system/talkgroup
Jan 31 19:45:40 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:40 newcall: system=102 talkgroup=35680 file=35680-1643676330_141675000-call_298.wav no matching system/talkgroup
Jan 31 19:45:43 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:43 newcall: system=102 talkgroup=35456 file=35456-1643676331_141525000-call_1838.wav no matching system/talkgroup
Jan 31 19:45:45 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:45 newcall: system=102 talkgroup=35232 file=35232-1643676339_142425000-call_1840.wav no matching system/talkgroup
Jan 31 19:45:47 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:47 newcall: system=102 talkgroup=35456 file=35456-1643676339_142005000-call_1841.wav no matching system/talkgroup
Jan 31 19:45:50 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:50 newcall: system=100 talkgroup=8896 file=8896-1643676340_141375000-call_1842.m4a success
Jan 31 19:45:50 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:50 newcall: system=102 talkgroup=35472 file=35472-1643676343_141525000-call_1844.wav no matching system/talkgroup
Jan 31 19:45:51 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:51 newcall: system=100 talkgroup=8896 file=8896-1643676340_142125000-call_299.wav duplicate call rejected
Jan 31 19:45:56 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:56 newcall: system=102 talkgroup=35440 file=35440-1643676339_141735000-call_1839.wav no matching system/talkgroup
Jan 31 19:45:57 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:57 newcall: system=102 talkgroup=35472 file=35472-1643676346_142425000-call_1845.wav no matching system/talkgroup
Jan 31 19:45:59 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:45:59 newcall: system=102 talkgroup=35232 file=35232-1643676343_142995000-call_1843.wav no matching system/talkgroup
Jan 31 19:46:03 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:03 newcall: system=201 talkgroup=2055 file=2055-1643676358_867387500-call_2727.m4a success
Jan 31 19:46:05 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:05 newcall: system=102 talkgroup=35232 file=35232-1643676356_141375000-call_1847.wav no matching system/talkgroup
Jan 31 19:46:08 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:08 newcall: system=102 talkgroup=35440 file=35440-1643676351_142005000-call_1846.wav no matching system/talkgroup
Jan 31 19:46:08 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:08 newcall: system=201 talkgroup=1506 file=1506-1643676338_867537500-call_2720.m4a success
Jan 31 19:46:08 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:08 newcall: system=102 talkgroup=35456 file=35456-1643676356_141525000-call_1848.wav no matching system/talkgroup
Jan 31 19:46:14 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:14 newcall: system=201 talkgroup=1528 file=1528-1643676370_867537500-call_2732.wav no matching system/talkgroup
Jan 31 19:46:14 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:14 newcall: system=102 talkgroup=35232 file=35232-1643676361_141735000-call_1849.wav no matching system/talkgroup
Jan 31 19:46:15 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:15 newcall: system=201 talkgroup=1503 file=1503-1643676368_867387500-call_2731.wav no matching system/talkgroup
Jan 31 19:46:15 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:15 newcall: system=102 talkgroup=35456 file=35456-1643676365_142425000-call_1850.wav no matching system/talkgroup
Jan 31 19:46:21 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:21 newcall: system=201 talkgroup=1528 file=1528-1643676374_867387500-call_2735.wav no matching system/talkgroup
Jan 31 19:46:22 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:22 newcall: system=102 talkgroup=35232 file=35232-1643676373_141375000-call_1852.wav no matching system/talkgroup
Jan 31 19:46:22 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:22 newcall: system=100 talkgroup=8896 file=8896-1643676372_141435000-call_300.m4a success
Jan 31 19:46:23 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:23 newcall: system=102 talkgroup=35440 file=35440-1643676374_142005000-call_1853.wav no matching system/talkgroup
Jan 31 19:46:23 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:23 newcall: system=201 talkgroup=1506 file=1506-1643676368_867637500-call_2730.m4a success
Jan 31 19:46:28 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:28 newcall: system=102 talkgroup=35456 file=35456-1643676379_142425000-call_1856.wav no matching system/talkgroup
Jan 31 19:46:29 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:29 newcall: system=100 talkgroup=8896 file=8896-1643676377_141525000-call_1854.m4a success
Jan 31 19:46:30 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:30 newcall: system=201 talkgroup=1506 file=1506-1643676383_867387500-call_2738.m4a success
Jan 31 19:46:31 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:31 newcall: system=100 talkgroup=8896 file=8896-1643676377_142950000-call_301.wav duplicate call rejected
Jan 31 19:46:34 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:34 newcall: system=201 talkgroup=1528 file=1528-1643676386_867537500-call_2740.wav no matching system/talkgroup
Jan 31 19:46:34 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:34 newcall: system=102 talkgroup=35440 file=35440-1643676387_141375000-call_1858.wav no matching system/talkgroup
Jan 31 19:46:37 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:37 newcall: system=201 talkgroup=1506 file=1506-1643676395_867537500-call_2741.m4a success
Jan 31 19:46:40 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:40 newcall: system=102 talkgroup=35232 file=35232-1643676377_141735000-call_1855.wav no matching system/talkgroup
Jan 31 19:46:40 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:40 newcall: system=102 talkgroup=35456 file=35456-1643676388_142005000-call_1859.wav no matching system/talkgroup
Jan 31 19:46:47 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:47 newcall: system=102 talkgroup=35456 file=35456-1643676397_142425000-call_1860.wav no matching system/talkgroup
Jan 31 19:46:51 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:51 newcall: system=102 talkgroup=35232 file=35232-1643676402_141525000-call_1861.wav no matching system/talkgroup
Jan 31 19:46:54 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:54 newcall: system=102 talkgroup=35472 file=35472-1643676406_141375000-call_1863.wav no matching system/talkgroup
Jan 31 19:46:55 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:46:55 newcall: system=201 talkgroup=1506 file=1506-1643676402_867637500-call_2744.m4a success
Jan 31 19:47:02 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:02 newcall: system=102 talkgroup=35472 file=35472-1643676410_141735000-call_1864.wav no matching system/talkgroup
Jan 31 19:47:06 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:06 newcall: system=100 talkgroup=8224 file=8224-1643676410_141675000-call_302.m4a success
Jan 31 19:47:06 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:06 newcall: system=201 talkgroup=1506 file=1506-1643676420_867387500-call_2748.m4a success
Jan 31 19:47:10 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:10 newcall: system=102 talkgroup=35472 file=35472-1643676422_142425000-call_1866.wav no matching system/talkgroup
Jan 31 19:47:12 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:12 newcall: system=201 talkgroup=1528 file=1528-1643676396_867537500-call_2742.wav no matching system/talkgroup
Jan 31 19:47:15 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:15 newcall: system=102 talkgroup=35472 file=35472-1643676425_141525000-call_1867.wav no matching system/talkgroup
Jan 31 19:47:22 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:22 newcall: system=201 talkgroup=1506 file=1506-1643676433_866887500-call_2753.m4a success
Jan 31 19:47:27 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:27 newcall: system=102 talkgroup=35472 file=35472-1643676439_141375000-call_1868.wav no matching system/talkgroup
Jan 31 19:47:30 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:30 newcall: system=102 talkgroup=35472 file=35472-1643676443_141735000-call_1870.wav no matching system/talkgroup
Jan 31 19:47:35 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:35 newcall: system=102 talkgroup=35472 file=35472-1643676446_142425000-call_1872.wav no matching system/talkgroup
Jan 31 19:47:36 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:36 newcall: system=201 talkgroup=1528 file=1528-1643676432_867387500-call_2752.wav no matching system/talkgroup
Jan 31 19:47:38 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:38 newcall: system=102 talkgroup=35440 file=35440-1643676449_141525000-call_1873.wav no matching system/talkgroup
Jan 31 19:47:39 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:39 newcall: system=102 talkgroup=35472 file=35472-1643676451_141375000-call_1874.wav no matching system/talkgroup
Jan 31 19:47:42 vmi767181 rdio-scanner[2440993]: 2022/01/31 19:47:42 newcall: system=100 talkgroup=8224 file=8224-1643676445_142125000-call_303.m4a success
Jan 31 19:47:42 vmi767181 rdio-scanner[2440993]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 31 19:47:42 vmi767181 rdio-scanner[2440993]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x975b54]
Jan 31 19:47:42 vmi767181 rdio-scanner[2440993]: goroutine 25 [running]:
Jan 31 19:47:42 vmi767181 rdio-scanner[2440993]: main.(*Controller).IngestCall(0xc000130f00, 0xc0002af440)
Jan 31 19:47:42 vmi767181 rdio-scanner[2440993]: #011/home/chuot/Dev/rdio-scanner/server/controller.go:214 +0x394
Jan 31 19:47:42 vmi767181 rdio-scanner[2440993]: main.(*Controller).Start.func2()
Jan 31 19:47:42 vmi767181 rdio-scanner[2440993]: #011/home/chuot/Dev/rdio-scanner/server/controller.go:641 +0x105
Jan 31 19:47:42 vmi767181 rdio-scanner[2440993]: created by main.(*Controller).Start
Jan 31 19:47:42 vmi767181 rdio-scanner[2440993]: #011/home/chuot/Dev/rdio-scanner/server/controller.go:637 +0x2d1
Jan 31 19:47:42 vmi767181 systemd[1]: rdio-scanner.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 31 19:47:42 vmi767181 systemd[1]: rdio-scanner.service: Failed with result 'exit-code'.

**Comment by chuot** [comment]
Fixed in the upcoming v6.1.9.
