### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by n8twj** [chuot/rdio-scanner#37]
pi@raspberrypi:~/rdio-scanner $ DEBUG=true node run.js
Building client app...
> rdio-scanner-client@5.0.4 build /home/pi/rdio-scanner/client
> ng build --base-href ./ --prod

Your global Angular CLI version (11.2.0) is greater than your local version (11.1.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
An unhandled exception occurred: Unexpected end of input
See "/tmp/ng-RZVLJf/angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! rdio-scanner-client@5.0.4 build: `ng build --base-href ./ --prod`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the rdio-scanner-client@5.0.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-02-15T22_09_22_955Z-debug.log

An error has occured. Please re-run the command like this: 'DEBUG=true node run.js'
pi@raspberrypi:~/rdio-scanner $ cat /tmp/ng-RZVLJf/angular-errors.log
[error] /home/pi/rdio-scanner/client/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:48790
                                var targetFile = getExternalModuleFile
                                                                      

SyntaxError: Unexpected end of input
    at wrapSafe (internal/modules/cjs/loader.js:1167:16)
    at Module._compile (internal/modules/cjs/loader.js:1215:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/pi/rdio-scanner/client/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:11:12)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/pi/rdio-scanner/client/node_modules/@angular-devkit/build-optimizer/src/index.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)

pi@raspberrypi:~/rdio-scanner $ npm -v
6.14.7
pi@raspberrypi:~/rdio-scanner $ node -v
v14.8.0
pi@raspberrypi:~/rdio-scanner $ cat /etc/debian_version 
10.3

**Comment by chuot** [comment]
I'm so sorry, I haven't had time to try to reproduce on a RPI. Have you tried installing on a fresh OS install with this helper script: https://github.com/chuot/rdio-scanner-pi-setup ?
